# Crack the Code!

![jigsaw from saw](https://images.fineartamerica.com/images/artworkimages/mediumlarge/3/i-want-to-play-a-game-jigsaw-saw-movie-remake-posters.jpg)

Answer the 10 questions below to reveal a hidden message at the bottom of the notebook.

 - Each answer is numeric, BUT YOU SHOULD WRITE CODE TO GET THE ANSWER.
 - For each question, store your code in a variable that's the same letter as the question (e.g. for the first question, you should have `a = <YOUR CODE>`)
 - Each correct answer reveals two words from a secret message at the bottom of the notebook.
 - Once the message is complete, you'll know what to do next.

Rules of the game:
 - Teams of 2. Both teammates must have all solutions to have finished.
 - You may not type on anybody else's keyboard. To share an answer, you can speak the code or show your screen.
 - Hints are provided for some questions.
 - If you're still stuck with your teammate, you may ask for help from another team.
 - If you're still stuck, then you can ask Prof Roth.
- Each answer is numeric, BUT YOU SHOULD WRITE CODE TO GET THE ANSWER. 
 - For each question, WRITE CODE TO FIND THE ANSWER and store the output in a variable with that's the letter of the question (e.g. the answer to a should be stored in a variable named a). Each answer reveals two words from the hidden message.

In [51]:
a, b, c, d, e, f, g, h, i, j = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [52]:
import pandas as pd
import numpy as np

In [53]:

data_url = "https://raw.githubusercontent.com/GettysburgDataScience/datasets/refs/heads/main/countypres_2000-2024.csv"
elec_df = pd.read_csv(data_url)

elec_df

,year,state,state_po,county_name,county_fips,office,candidate,party,candidatevotes,totalvotes,version,mode
0,2000,ALABAMA,AL,AUTAUGA,1001.0,US PRESIDENT,AL GORE,DEMOCRAT,4942,17208,20250821,TOTAL
1,2000,ALABAMA,AL,AUTAUGA,1001.0,US PRESIDENT,GEORGE W. BUSH,REPUBLICAN,11993,17208,20250821,TOTAL
2,2000,ALABAMA,AL,AUTAUGA,1001.0,US PRESIDENT,OTHER,OTHER,113,17208,20250821,TOTAL
3,2000,ALABAMA,AL,AUTAUGA,1001.0,US PRESIDENT,RALPH NADER,GREEN,160,17208,20250821,TOTAL
4,2000,ALABAMA,AL,BALDWIN,1003.0,US PRESIDENT,AL GORE,DEMOCRAT,13997,56480,20250821,TOTAL
...,...,...,...,...,...,...,...,...,...,...,...,...
94404,2024,WYOMING,WY,WESTON,56045.0,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,3069,3512,20250821,NaN
94405,2024,WYOMING,WY,WESTON,56045.0,US PRESIDENT,KAMALA D HARRIS,DEMOCRAT,378,3512,20250821,NaN
94406,2024,WYOMING,WY,WESTON,56045.0,US PRESIDENT,OTHER,OTHER,18,3512,20250821,NaN
94407,2024,WYOMING,WY,WESTON,56045.0,US PRESIDENT,OVERVOTES,NaN,1,3512,20250821,NaN
94408,2024,WYOMING,WY,WESTON,56045.0,US PRESIDENT,UNDERVOTES,NaN,20,3512,20250821,NaN

## Note

The way election tallies were reported changed in 2020. Prior to 2020, only Total counts are provided. In the 2020 and 2024 elections, some states provide breakdowns by voting method (e.g. absentee, provisional), but the nomenclature varies by state.

In [54]:
modes = {}

modes['state'] = []
for year in range(2000,2025, 4):
    modes[str(year)] = []
        
for state in elec_df['state_po'].unique():
    modes['state'].append(state)
    
    for year in range(2000, 2025, 4):
        modes[str(year)].append(elec_df.query("state_po == @state and year==@year")['mode'].unique())
   
voting_modes = pd.DataFrame(modes)
voting_modes.tail(50)

,state,2000,2004,2008,2012,2016,2020,2024
1,AK,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL VOTES]
2,AZ,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],"[EARLY VOTE, ELECTION DAY, PROVISIONAL]","[EARLY VOTING, ELECTION DAY, PROVISIONAL, TOTA..."
3,AR,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],"[ABSENTEE, EARLY VOTE, ELECTION DAY, PROVISIONAL]","[ABSENTEE, EARLY VOTING, ELECTION DAY, PROVISI..."
4,CA,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL VOTES]
5,CO,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL VOTES]
6,CT,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL VOTES]
7,DE,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL VOTES]
8,DC,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL VOTES]
9,FL,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL VOTES]
10,GA,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],"[ABSENTEE, ADVANCED VOTING, ELECTION DAY, PROV]",[TOTAL VOTES]
11,HI,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL VOTES]
12,ID,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[nan]
13,IL,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL VOTES]
14,IN,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL VOTES]
15,IA,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],"[ABSENTEE, ELECTION DAY]","[ABSENTEE, ELECTION DAY, TOTAL VOTES]"
16,KS,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[nan]
17,KY,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[ELECTION DAY],[TOTAL VOTES]
18,LA,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],"[EARLY VOTING, PROVISIONAL, TOTAL VOTES]"
19,ME,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL VOTES]
20,MD,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],"[2ND ABSENTEE, ABSENTEE, EARLY VOTING, ELECTIO...",[TOTAL VOTES]
21,MA,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL VOTES]
22,MI,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL VOTES]
23,MN,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL VOTES]
24,MS,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL VOTES]
25,MO,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL VOTES]
26,MT,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL VOTES]
27,NE,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL VOTES]
28,NV,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL VOTES]
29,NH,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL VOTES]
30,NJ,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL VOTES]
31,NM,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],"[ABSENTEE, EARLY VOTING, ELECTION DAY]"
32,NY,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL VOTES]
33,NC,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],"[ABSENTEE BY MAIL, ELECTION DAY, ONE STOP, PRO...",[nan]
34,ND,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL VOTES]
35,OH,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL VOTES]
36,OK,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],"[ABSENTEE BY MAIL, EARLY, ELECTION DAY]","[ABSENTEE, EARLY VOTING, ELECTION DAY, TOTAL V..."
37,OR,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL VOTES]
38,PA,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],"[ELECTION DAY, MAIL-IN, PROVISIONAL, TOTAL VOTES]"
39,RI,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[nan]
40,SC,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],"[ABSENTEE BY MAIL, ELECTION DAY, FAILSAFE, FAI...","[ABSENTEE, EARLY VOTING, ELECTION DAY, FAILSAF..."
41,SD,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],"[TOTAL VOTES, VOTE CENTER]"
42,TN,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL VOTES]
43,TX,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],"[nan, EARLY VOTING, TOTAL VOTES]"
44,UT,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],"[EARLY, ELECTION DAY, MAIL, TOTAL]",[nan]
45,VT,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[nan]
46,VA,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],"[ABSENTEE, ELECTION DAY, PROVISIONAL]",[TOTAL VOTES]
47,WA,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[nan]
48,WV,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[nan]
49,WI,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[nan]
50,WY,[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[TOTAL],[nan]

## CLUES! Part I

 The first batch of questions use the presidential election data above. Each answer is numeric, BUT YOU SHOULD WRITE CODE TO GET THE ANSWER. 
 For each question, WRITE CODE TO FIND THE ANSWER and store the output in a variable with that's the letter of the question (e.g. the answer to a should be stored in a variable named a). Each answer reveals two words from the hidden message.

**a.** What number is in the row with index 189 under the column 'candidatevotes'?

<details>
<summary>Click to reveal hint</summary>
 - Use ```.iloc[]```
</details>

**b.** In 2024, how many election day (not mail-in or provisional) votes did DJT get in Adams County, PA? 

<details>
<summary>Click to reveal hint</summary>
 - Use ```.query()``` to filter the year, candidate, county, and mode.
</details>

**c.** What is the county_fips of the Pennsylvania county with the greatest percentage of third party votes?

<details>
<summary>Click to reveal hint</summary>
   
   - Create a new dataframe of only rows corresponding to PA results from the 2024 election where the mode is "TOTAL VOTES" and the party is neither "REPUBLICAN" or "DEMOCRAT".
    
   - Create a column called "percent vote" to this dataframe calculating the percent vote each candidate got.  
  
   - Groupby 'county_name' and aggregate the percentages as a 'sum'. To keep the 'county_fips' column, aggregate that column with 'first'.  
  
   - Sort the results by "percent vote" and select the fips corresponding to the greatest percentage using `.loc[]` or `.iloc`. 
</details>

d. How many more votes were cast in PA in the 2020 election than the 2016 election?

<details>
<summary>Click to reveal hint</summary>
   - No hint. YOU GOT THIS!
</details>

e. In the 2000 election, by how many votes did the Republican party LOSE Florida? (this should be a positive number...they won, but it was a long legal battle)

<details>
<summary>Click to reveal not a hint</summary>

   [One of the craziest elections ever!](https://en.wikipedia.org/wiki/2000_United_States_presidential_election) The vote differential in this wikipedia article is not the one you'll get from the data.

</details>

## MORE CLUES! Part II

The next batch of questions use the Washington State Electric Vehicle registry.

In [50]:
url = 'https://raw.githubusercontent.com/GettysburgDataScience/datasets/refs/heads/main/Electric_Vehicle_WA.csv'

ev_df = pd.read_csv(url)

ev_df.fillna(0, inplace = True)
ev_df['Electric Range'] = ev_df['Electric Range'].astype(int)

ev_df.head()

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,WA1E2AFY8R,Thurston,Olympia,WA,98512.0,2024,AUDI,Q5 E,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,23,0,22.0,263239938,POINT (-122.90787 46.9461),PUGET SOUND ENERGY INC,5.306701e+10
1,WAUUPBFF4J,Yakima,Wapato,WA,98951.0,2018,AUDI,A3,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,16,0,15.0,318160860,POINT (-120.42083 46.44779),PACIFICORP,5.307794e+10
2,1N4AZ0CP0F,King,Seattle,WA,98125.0,2015,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,84,0,46.0,184963586,POINT (-122.30253 47.72656),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303300e+10
3,WA1VAAGE5K,King,Kent,WA,98031.0,2019,AUDI,E-TRON,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,204,0,11.0,259426821,POINT (-122.17743 47.41185),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303303e+10
4,7SAXCAE57N,Snohomish,Bothell,WA,98021.0,2022,TESLA,MODEL X,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,1.0,208182236,POINT (-122.18384 47.8031),PUGET SOUND ENERGY INC,5.306105e+10


**f.** What is the maximum Electric Range of the vehicles in this dataset?

<details>
<summary>Click to reveal hint</summary>
   
   - Use `.query()` and `.max()`
</details>

**g.** How many 2024 Tesla Model Ys are in King County?

<details>
<summary>Click to reveal hint</summary>
   - Use `.query()` and then selecting the 'DOL Vehicle ID' column, apply `.nunique()`
</details>

**h.** For the Model Year that has the most registered vehicles, how many vehicles are there?

<details>
<summary>Click to reveal hint</summary>
   
   - Groupby 'Model Year', then aggregate 'DOL Vehicle ID' with 'count'.
   - Sort the values and pick the greatest count. 
</details>

**i.** Of Chevrolet EVs, what is the count for the most popular model?

<details>
<summary>Click to reveal hint</summary>
   
   - Filter to only Chevy cars.
    
   - Groupby the model and count the DOL Vehicle IDs 
  
   - Sort the values and select the greatest number.
  </details>

**j.** What is the DOL Vehicle ID of the oldest car on this registry? There are two entries (likely a data entry mistake), pick the smaller number DOL Vehicle ID.

In [55]:


def decode_word(codestr, ans):
    np.random.seed(ans)
    number = np.random.randint(0, 1000000000)
    
    numberstr = str(number)
    decoded = ''
    while codestr:
        code = int(codestr[0:3])
        num = numberstr[0]     

        char = chr(code - (int(num)+1)*ord(num))
        decoded += char
        
        try:
            codestr = codestr[3:]
        except:
            pass
        
        if len(numberstr) == 1:
            continue
        else:
            numberstr = numberstr[1:]
        
    return decoded

def decode_message(encoded_message, ans_list):
    code_list = encoded_message.split()
    word_list = []
    for code, ans in zip(code_list, ans_list):
        
        if isinstance(ans, pd.core.frame.DataFrame):
            ans = ans.iat[0,0]
        elif isinstance(ans, pd.core.series.Series):
            ans = ans.iat[0]
            
        if not isinstance(ans, int):
            try:
                ans = int(ans)
            except: pass
        
        try:
            word_list.append(decode_word(code, ans))
        except:
            word_list.append('_' * int(len(code)/3))           
    return ' '.join(word_list)

## THE SECRET MESSAGE

In [56]:
secret_message_a = '237202361314 439489165137378251 304305197489360361670 686308309555 509228234171522273 613251619163301543251614 672475257671 601 213488419305440361 174649525572226407616'
secret_message_b = '171609548612 195493425 543582671199360 667 620255619163321541213609 522251262206561 609325305555479 309314 415488159214364251162 258195370307377601151305424'
ans = [f, a, b, i, h, c, e, d, j, g]

message_a = decode_message(secret_message_a, ans)
message_b = decode_message(secret_message_b, ans[::-1])

print(f'Instruction 1: {message_a}')
print(f'Instruction 2: {message_b}')

Instruction 1: ____ ______ _______ ____ ______ ________ ____ ǃ ______ _______
Instruction 2: ____ ___ _____ ȅ ________ _____ _____ Ċ _______ _________