# PS05
Name: Professor Roth 

Collaborators:
 - DS 256 Students

DS256, Gettysburg College  
Prof Eatai Roth  
**Due: Mon, Mar 30, 2026 at 1:10p**

By submitting this work, you attest that: 
 - it reflects your own effort and understanding of the material
 - you did not ask for help from students outside the course, other than PLAs
 - you did not use a generative AI to produce any code used below.

 

**THE GOOD, THE BAD, THE UGLY**
(Actually, the Pretty, the Ugly, the Good)

In the problems below, you are given three data sets from which you will be creating graphs. You will be creating one of:
 - Pretty - the prettiest graph you can make
 - Ugly - the ugliest graph you can make (think beyond color, though colors will likely be choices you make)
 - Best - the best graph you can make. What makes a good graph? Clear, understandable, labeled, uncluttered. Ask for opinions from classmates and Prof Roth.

You will be making one each of Pretty and Ugly and two of Best, but you may choose which dataset gets what.

**Problem 1 - 2024 Election Results**

The dataframe elec_df contains county-level results from each presidential election since 2000.   
Create a side-by-side bar graph that shows votes cast for both the democratic candidate and the republican candidate by county for just PENNSYLVANIA in the 2024 election.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
elec_df = pd.read_csv('https://raw.githubusercontent.com/GettysburgDataScience/datasets/refs/heads/main/countypres_2000-2024.csv')

In [3]:
elec_df.head(2)

,year,state,state_po,county_name,county_fips,office,candidate,party,candidatevotes,totalvotes,version,mode
0,2000,ALABAMA,AL,AUTAUGA,1001.0,US PRESIDENT,AL GORE,DEMOCRAT,4942,17208,20250821,TOTAL
1,2000,ALABAMA,AL,AUTAUGA,1001.0,US PRESIDENT,GEORGE W. BUSH,REPUBLICAN,11993,17208,20250821,TOTAL

In [4]:
pa_df = elec_df.query('state == "PENNSYLVANIA" and year==2024 and mode == "TOTAL VOTES"')

In [5]:
pa_D = pa_df.query('party == "DEMOCRAT"')
pa_R = pa_df.query('party == "REPUBLICAN"')

In [6]:
pa_D

,year,state,state_po,county_name,county_fips,office,candidate,party,candidatevotes,totalvotes,version,mode
87157,2024,PENNSYLVANIA,PA,ADAMS,42001.0,US PRESIDENT,KAMALA D HARRIS,DEMOCRAT,19842,121300,20250821,TOTAL VOTES
87173,2024,PENNSYLVANIA,PA,ALLEGHENY,42003.0,US PRESIDENT,KAMALA D HARRIS,DEMOCRAT,429916,1441008,20250821,TOTAL VOTES
87189,2024,PENNSYLVANIA,PA,ARMSTRONG,42005.0,US PRESIDENT,KAMALA D HARRIS,DEMOCRAT,8553,74238,20250821,TOTAL VOTES
87205,2024,PENNSYLVANIA,PA,BEAVER,42007.0,US PRESIDENT,KAMALA D HARRIS,DEMOCRAT,37196,189686,20250821,TOTAL VOTES
87221,2024,PENNSYLVANIA,PA,BEDFORD,42009.0,US PRESIDENT,KAMALA D HARRIS,DEMOCRAT,4336,56320,20250821,TOTAL VOTES
...,...,...,...,...,...,...,...,...,...,...,...,...
88149,2024,PENNSYLVANIA,PA,WASHINGTON,42125.0,US PRESIDENT,KAMALA D HARRIS,DEMOCRAT,44910,243234,20250821,TOTAL VOTES
88165,2024,PENNSYLVANIA,PA,WAYNE,42127.0,US PRESIDENT,KAMALA D HARRIS,DEMOCRAT,9150,58888,20250821,TOTAL VOTES
88181,2024,PENNSYLVANIA,PA,WESTMORELAND,42129.0,US PRESIDENT,KAMALA D HARRIS,DEMOCRAT,74904,422900,20250821,TOTAL VOTES
88197,2024,PENNSYLVANIA,PA,WYOMING,42131.0,US PRESIDENT,KAMALA D HARRIS,DEMOCRAT,4680,30104,20250821,TOTAL VOTES
88213,2024,PENNSYLVANIA,PA,YORK,42133.0,US PRESIDENT,KAMALA D HARRIS,DEMOCRAT,91926,498420,20250821,TOTAL VOTES

**Problem 2 - MCU Movie Box Office**

The dataframe mcu_df contains information about box office draws of the MCU movies up through 2024.   
Create a stacked barplot showing earnings of movies broken down by domestic and international box office values.

In [8]:
mcu_df = pd.read_csv('https://raw.githubusercontent.com/GettysburgDataScience/datasets/refs/heads/main/mcu.csv')
mcu_df.head(2)

,Unnamed: 0,movie_title,Type,mcu_phase_number,mcu_phase_text,release_date,release_year,rt_tomato_meter,rt_audience_score,imdb-rating,metacritic_metascore,metacritic_userscore,production,domestic,international,worldwide
0,0,Iron Man,Movie,1.0,MCU Phase 1,5/2/08,2008.0,94.0,91.0,7.9,79.0,8.6,140000000.0,319034126.0,266762121.0,585796247.0
1,1,The Incredible Hulk,Movie,1.0,MCU Phase 1,6/13/08,2008.0,67.0,70.0,6.6,61.0,6.8,140000000.0,134806913.0,128620638.0,263427551.0

**Problem 3 - King County Housing Data**

The dataframe kc_df contains information about properties sold in King County, WA in 2014.   

Create an overlayed histogram comparing the distribution of house prices for 2, 3, 4, and 5 bedroom homes.

In [ ]:
kc_df = pd.read_csv('https://raw.githubusercontent.com/GettysburgDataScience/datasets/refs/heads/main/kc_house_data.csv')

**Problem 4 - Gettysburg Weather**

The dataframe weather_df contains historic weather data from the local area.   

Make a line graph showing daily highs comparing the years 1990, 2000, 2010, and 2020.

In [ ]:
weather_df = pd.read_csv('https://raw.githubusercontent.com/GettysburgDataScience/datasets/refs/heads/main/gettysburg_weather.csv')